// <auto-generated />
using System;
using BoardGameRent.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BoardGameRent.Web.Migrations
{
    [DbContext(typeof(BoardGameDbContext))]
    [Migration("20260707161009_SetupContext")]
    partial class SetupContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("BoardGameRent.Web.Models.Juego", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstaDisponible")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecioPorDia")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Juegos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Descripcion = "enjoy your game",
                            EstaDisponible = true,
                            ImageUrl = "https://devirinvestments.s3.eu-west-1.amazonaws.com/img/catalog/product/8436017220100-1200-face3d.jpg",
                            Nombre = "Catan",
                            PrecioPorDia = 3000m
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Descripcion = "enjoy your game",
                            EstaDisponible = true,
                            ImageUrl = "https://acdn-us.mitiendanube.com/stores/001/750/716/products/dixit_01-755cf40946eda097de17097563234968-640-0.webp",
                            Nombre = "Dixit",
                            PrecioPorDia = 1000m
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Descripcion = "enjoy your game",
                            EstaDisponible = true,
                            ImageUrl = "https://acdn-us.mitiendanube.com/stores/001/029/049/products/cajitas-elegidas-parte-7-63-716b6f763d3bdfd50017516475086918-640-0.webp",
                            Nombre = "Carcassonne",
                            PrecioPorDia = 1000m
                        });
                });

            modelBuilder.Entity("BoardGameRent.Web.Models.RegistroAlquiler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Duracion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaAlquiler")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaDevolucion")
                        .HasColumnType("TEXT");

                    b.Property<int>("JuegoId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PrecioFinal")
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("JuegoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("RegistrosAlquiler");
                });

            modelBuilder.Entity("BoardGameRent.Web.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellido")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCompleto")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rol")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellido = "Cacas",
                            Dni = "43023456",
                            Email = "rocioevelyndure@gmail.com",
                            NombreCompleto = "Melody Luz",
                            Rol = 0,
                            Telefono = "4234567"
                        });
                });

            modelBuilder.Entity("BoardGameRent.Web.Models.RegistroAlquiler", b =>
                {
                    b.HasOne("BoardGameRent.Web.Models.Juego", "Juego")
                        .WithMany()
                        .HasForeignKey("JuegoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BoardGameRent.Web.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Juego");

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
